services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/MelodyMasterQuiz

    working_dir: /MelodyMasterQuiz

    command: python manage.py runserver 0.0.0.0:8000
