# Generated by Django 4.2.4 on 2023-09-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MelodyQuizApp', '0003_user_gamestatistic_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(default='https://open.spotify.com/playlist/5j0BqpHr14wEGjVEGLvgen?si=e99ecaeedc12440b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MelodyQuizApp.question')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomPlaylists.playlist')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MelodyQuizApp.gamestatistic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
